### ISSUE TITLE
Cannot decrypt some dlsts

### ISSUE THREAD

**Issue by f0banzai** [llc1123/dlsite-key-dumper#1]
e.g. BJ218577
There are some outputs:
G:\DB\Image\RAWS>dlsite-key-dumper.exe "妻という世界 ～俺が味わう彼女の快楽～.dlst"
Traceback (most recent call last):
  File "main.py", line 56, in <module>
  File "main.py", line 51, in main
  File "dlsite_decrypter\dlsite_kts.py", line 49, in export_package_content
  File "dlsite_decrypter\crypto_ops.py", line 93, in decrypt_file_from_bytes
  File "dlsite_decrypter\crypto_ops.py", line 8, in generate_ivs
  File "lib\site-packages\Crypto\Cipher\AES.py", line 232, in new
  File "lib\site-packages\Crypto\Cipher\__init__.py", line 79, in _create_cipher
  File "lib\site-packages\Crypto\Cipher\_mode_ecb.py", line 215, in _create_ecb_cipher
  File "lib\site-packages\Crypto\Cipher\AES.py", line 93, in _create_base_cipher
ValueError: Incorrect AES key length (0 bytes)
[29500] Failed to execute script main

**Comment by llc1123** [comment]
Known issue. Reverse engineering of the newer versions needed.
